# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

[book]
authors = ["lowRISC"]
language = "en"
multilingual = false
src = "."
title = "OpenTitan Documentation"

[output.html]
fold = { enable = true, level = 1 }
git-repository-url = "https://github.com/lowrisc/opentitan"
edit-url-template = "https://github.com/lowrisc/opentitan/edit/master/{path}"
curly-quotes = true

[preprocessor.readme2index]
command = "./util/mdbook_readme2index.py"
